server:
  defaultPort: 5050
  allowedOrigins: '*'
  allowedMethods: 'GET, POST, DELETE, PUT, PATCH, TRACE'
  allowedHeaders: Origin, Content-Type, Accept, Authorization, X-localization, Proxy-Authorization
  contentType: 'application/json'
jdbc:
  url: jdbc:mariadb://localhost:63306/dboSecurity
  driverClassName: org.mariadb.jdbc.Driver
  username: dboSecurity
  password: mdn9VBYldGcmLo01lt5Y3lpQqeE=
  autoCommit: true
  allowPoolSuspension: true
  loginTimeout: 30000
  connectionTimeoutMs: 30000
  idleTimeoutMs: 600000
  maxLifetimeMs: 18000000
  mapperPackage: za.co.ratpack.finance.reactive.domain.mybatis.dao
  flywaySchema: dboSecurity
  migrationsTable: MIGRATION_SCHEMAS_HISTORY
  validateOnMigrationNaming: true
  validateOnMigrate: true
  createSchemas: false
  cleanDisabled: true
  baselineOnMigrate: true
  migrationLocation: db/migration
attestation:
  issuer: 'Security Authority'
  expirationTime: 900000
  secret: '6yFnLgisYlYfg/p3uNZ/aFlg/d0='
