-- Flyway migration script: V20241227020415__createSecWebauthRegistrionSequenceWithTable.sql
-- Author: Mark Mngoma
-- Created on: 2024-12-27 02:04:15
-- Add your SQL migration statements here.
CREATE SEQUENCE IF NOT EXISTS dboSecurity.SEC_WEB_AUTH_REGISTRATION_SEQ START WITH 1 INCREMENT BY 1 CACHE 1 NOCYCLE;

CREATE TABLE IF NOT EXISTS dboSecurity.SEC_WEB_AUTH_REGISTRATION_SEQ (
  ID BIGINT UNSIGNED PRIMARY KEY DEFAULT NEXTVAL(dboSecurity.SEC_WEB_AUTH_REGISTRATION_SEQ),
  ATTESTATION VARCHAR(255) NOT NULL,
  CLIENT_DATA VARCHAR(255) NOT NULL,
  VERIFY_USER BIT NOT NULL,
  CHALLENGE VARCHAR(255) NOT NULL,
  HOST_NAME VARCHAR(255) NOT NULL,
  PORT INT UNSIGNED NOT NULL,
  USER_AGENT VARCHAR(255) NOT NULL,
  USER_IP VARCHAR(255) NOT NULL,
  USER_COUNTRY VARCHAR(2) NOT NULL,
  USER_REGION VARCHAR(5) NOT NULL,
  USER_CITY VARCHAR(100) NOT NULL,
  USER_TZ VARCHAR(50) NOT NULL,
  REGISTER_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  EXPIRATION_DATE TIMESTAMP NOT NULL,
  ARCHIVED BIT NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL,
  CREATED_BY INT UNSIGNED NOT NULL,
  UPDATED_AT TIMESTAMP NULL DEFAULT NULL,
  UPDATED_BY INT UNSIGNED DEFAULT NULL
);
